-- 1. Create table if it doesn't exist
create table if not exists quran_progress (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  student_id text not null,
  week int not null,      
  type text not null,     -- 'hifz' or 'murajaah'
  goal text,              
  status text,            -- 'pending', 'completed', 'failed'
  note text,              
  month text not null,    
  year int not null,      
  unique(student_id, week, type, month, year)
);

-- 2. Open Permissions (RLS)
ALTER TABLE quran_progress ENABLE ROW LEVEL SECURITY;

-- Drop old policies to avoid duplicates
DROP POLICY IF EXISTS "Allow anon select quran" ON quran_progress;
DROP POLICY IF EXISTS "Allow anon insert quran" ON quran_progress;
DROP POLICY IF EXISTS "Allow anon update quran" ON quran_progress;
DROP POLICY IF EXISTS "Enable insert for authenticated users" ON quran_progress;
DROP POLICY IF EXISTS "Enable update for authenticated users" ON quran_progress;
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON quran_progress;

-- Create Permissive Policies (Write access for Anon/Dashboard)
CREATE POLICY "Allow anon select quran" ON quran_progress FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow anon insert quran" ON quran_progress FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Allow anon update quran" ON quran_progress FOR UPDATE TO anon, authenticated USING (true);
