-- AL-MADRASA DATABASE SCHEMA
-- Run this SQL in your Supabase Dashboard > SQL Editor

-- 1. ABSENCES TABLE
-- Tracks daily attendance per student
create table if not exists absences (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  student_id text not null, -- Assuming links to students.id (which might be uuid or text)
  date date not null,
  reason text not null, -- 'Aanwezig', 'Te Laat', 'Afwezig'
  group_name text
);

-- Index for faster lookup by date and student
create index if not exists idx_absences_date on absences(date);
create index if not exists idx_absences_student on absences(student_id);


-- 2. QURAN PROGRESS TABLE
-- Tracks hifz and muraja'ah goals per week
create table if not exists quran_progress (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  student_id text not null,
  week int not null,      -- 1, 2, 3, 4
  type text not null,     -- 'hifz' or 'murajaah'
  goal text,              -- The target, e.g. "Surah An-Naba"
  status text,            -- 'pending', 'completed', 'failed'
  note text,              -- Teacher comments
  month text not null,    -- e.g. 'Januari' (Should ideally be int, but using text for MVP consistency)
  year int not null,      -- e.g. 2026
  
  -- Constraint to ensure one entry per type/week/student/month
  unique(student_id, week, type, month, year)
);

-- Index for fetching progress
create index if not exists idx_quran_progress_student on quran_progress(student_id);

-- 3. ROW LEVEL SECURITY (Optional/Recommended)
-- Enable RLS
alter table absences enable row level security;
alter table quran_progress enable row level security;

-- Simple policies (Adjust based on your Auth setup)
-- Allow authenticated users (teachers/admins) to read/write
create policy "Enable read access for authenticated users" on absences for select using (auth.role() = 'authenticated');
create policy "Enable insert for authenticated users" on absences for insert with check (auth.role() = 'authenticated');
create policy "Enable update for authenticated users" on absences for update using (auth.role() = 'authenticated');
create policy "Enable delete for authenticated users" on absences for delete using (auth.role() = 'authenticated');

create policy "Enable read access for authenticated users" on quran_progress for select using (auth.role() = 'authenticated');
create policy "Enable insert for authenticated users" on quran_progress for insert with check (auth.role() = 'authenticated');
create policy "Enable update for authenticated users" on quran_progress for update using (auth.role() = 'authenticated');
